### ISSUE TITLE
Mage.php patching seems broken

### ISSUE THREAD

**Issue by jdchmiel** [Cotya/magento-composer-installer#103]
The contents of the file after patching are:
```
<?php 
require __DIR__ . '/bootstrap.php;
```
(note missing trailing single quote)
and the patching process seems to leave Mage.bootloader.php and Mage.class.php in the app folder of the magento install.
I am trying to do this with magento 1.9.2.4. 

My composer.json is relatively simple still:
{
    "require": {
        "aydin-hassan/magento-core-composer-installer": "^1.3",
        "magento-hackathon/magento-composer-installer": "3.0",
        "magento/magento": "1.9.2.4b",
	"mongodb/mongodb": "1.0.1",
	"jdchmiel/mongogento": "@dev"
    },
    "repositories": {
        "firegento": {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        "magento": {
            "type": "composer",
            "url": "https?://packages.magento.com"
        },
	"jdchmiel": {
            "type": "vcs",
	    "url": "git@github.com:jdchmiel/magento-mirror.git"
	},
	"jdchmiel-php": {
            "type": "git",
	    "url": "git@github.com:jdchmiel/mongogento.git"
	}
    },
    "extra": {
        "magento-root-dir": "mage_root/",
        "auto-append-gitignore": true,
	"magento-deploystrategy":"copy"
    }
}

Anything obvious I am missing?

**Comment by AydinHassan** [comment]
Looks like you have an old version of the installer. What version of `magento-hackathon/magento-composer-installer` do you have installed?

You can run `composer show --installed | grep magento-hackathon/magento-composer-installer` in your project root.

**Comment by AydinHassan** [comment]
Oh you have it pinned at exactly `3.0`. Change your requirement to `^3.0` and run `composer update`

**Comment by jdchmiel** [comment]
Awesome, that was the exact issue, thank you so much!

**Comment by AydinHassan** [comment]
@jdchmiel No problem :)
