### ISSUE TITLE
How to support the feature of 'git submodule' ?

### ISSUE THREAD

**Issue by yssource** [Cotya/magento-composer-installer#104]
I need to install "colinmollenhour/cache-backend-redis", which is depended on the submodule "colinmollenhour/credis". 
In fact, the composer is not supported with the feature git submodule.
I try to solve the problem by adding the following codes in composer.json at project's root directory.

```
    "scripts": {
        "post-install-cmd": [
            "cd vendor/colinmollenhour/cache-backend-redis && git submodule init && git submodule update"
        ],
        "post-update-cmd": [
            "cd vendor/colinmollenhour/cache-backend-redis && git submodule init && git submodule update"
        ]
    }
```
However, it does not work, and it will not git pull the "colinmollenhour/credis" as a submodule.
Is there any way to do with this installer?

**Comment by Flyingmana** [comment]
the installer does not support any git submodule related feature. The only advice I can give, is to request them to add the dependency as a composer dependency to their package.
