### ISSUE TITLE
After Update - PHP Fatal error:  Call to a member function getJob()

### ISSUE THREAD

**Issue by nuzil** [Cotya/magento-composer-installer#109]
Hello, After last update of magento-composer-installer, we are now getting this error when running 

composer update 

:
PHP Fatal error:  Call to a member function getJob() on a non-object in /home/dev/public_html/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 262

Fatal error: Call to a member function getJob() on a non-object in /home/dev/public_html/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 262

Somebody have an Idea? 

Thanks a lot

**Comment by razbakov** [comment]
have the same error

**Comment by razbakov** [comment]
i've tried to use 3.0.6 version and i've got this error:

```
[Exception]
  Dont update the "magento-hackathon/magento-composer-installer" with active
  plugins.
  Consult the documentation on how to update the Installer
  https://github.com/Cotya/magento-composer-installer#update-the-installer
```

**Comment by Flyingmana** [comment]
yeah, I did some "experimental" changes on the main branch, it seems I use some parts,which change between composer versions.

The exception of @razbakov is self explaining, when having the installer installed, and you want to "update" or in this case, downgrade it, you are now forced to follow the documentation and disable plugins.
