### ISSUE TITLE
Question: Event (hook) after all modules are installed

### ISSUE THREAD

**Issue by homecoded** [Cotya/magento-composer-installer#110]
Hello,

How can I create a hook that is called after all Magento modules are deployed to the magento root folder? Is there any way to achieve this?

Details: 

I would like to run a few scripts AFTER all magento modules are installed. I tried it via custom plugin and triggering scripts in different events. Unfortunately, I could not find any event 'late' enough, where the modules' code were already available in the magento root folder. Latest event I could find was the ```post-autoload-dump``` but that is fired before magento-composer-installer copies/links the module files into the magento root.

Next thing I tried was using a ```post-install-cmd``` in the ```scripts```-section of the root ```composer.json```. Interestingly, on a clean ```composer install``` (no vendor, no magento root, no composer.lock) that script is not called. If I call ```composer install``` again it IS called. This is not feeling right.

Thanks!

**Comment by AydinHassan** [comment]
@homecoded  `post-install-cmd` is only triggered on an install, when you have no `composer.lock` file you are not actually doing an install, despite type `composer-install`, you are doing an `update`. Installs only occur if there is a `composer.lock` file available.

The solution to your problem is to just listen to `post-install-cmd` as well as `post-update-cmd`.

Refs: https://getcomposer.org/doc/articles/scripts.md#command-events

**Comment by homecoded** [comment]
Hello @AydinHassan . Thank you for your feedback. That solved it for me. I got the events mixed up. Classical case of RTFM and I am genuinely embarrassed as I should be. 

It does leave me confused, though:

If I delete vendor folder and composer.lock and run ```composer install``` the ```post-update-cmd```is triggered. If composer.lock and vendor folder exist the ```post-install-cmd`` is triggered. I absolutely would have expected this to be the other way round.

From the docs:

_post-install-cmd_: occurs after the install command has been executed **with a lock file present**.
_post-update-cmd_: occurs after the update command has been executed, or after the install command has been executed **without a lock file present**.

Still, your proposal to implement both commands solved my issue. I was trying to solve clean installs first, then updates. That's why I did not yet look into the post update command.

And, most importantly, this is not an issue with magento-composer-installer.
