### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by luckyraul** [Cotya/magento-composer-installer#118]
Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate declared at /vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\PackageEvent but pre-package-update events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317

**Comment by Flyingmana** [comment]
thx, a new version which fixes this will be released next weekend

**Comment by hgati** [comment]
same too me.

 - Updating aschroder/smtp_pro (dev-master a1f9623 => 2.0.7) Checking out 5101ed278d
Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate declared at /var/www/htdocs/magento1.7.0.2/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\PackageEvent but pre-package-update events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:317

**Comment by aadmathijssen** [comment]
Hi,

Do you know if there is any update on this issue?

Thanks!

BTW I encountered the deprecation notices after upgrading to Composer 1.3.0 (released on the 24 Dec 2016). The deprecation notices are also present in newer Composer 1.3.x versions.

**Comment by Flyingmana** [comment]
It should be fixed in 3.1.0, could anyone validate this?

**Comment by peterjaap** [comment]
Confirmed.

You should also update the docs; https://github.com/Cotya/magento-composer-installer#update-the-installer (it still says 3.0 instead of 3.1)

**Comment by aadmathijssen** [comment]
Confirmed.

Thanks!
