### ISSUE TITLE
Command integrator... not integrated?

### ISSUE THREAD

**Issue by nevvermind** [Cotya/magento-composer-installer#12]
I'm looking at these three commands - https://github.com/Cotya/magento-composer-installer/tree/3.0/src/MagentoHackathon/Composer/Magento/Command - but I don't see the [command integrator](https://github.com/magento-hackathon/composer-command-integrator) required anywhere. Are they still available?

**Comment by Flyingmana** [comment]
Yeah, I did not remove the code yet, but it should not be needed anymore.
a new deploy can now get triggered with ```composer.phar run-script post-install-cmd -vvv -- --redeploy```

I need to find a more popular place in the documentation for it then only in the part about deploying

**Comment by nevvermind** [comment]
Right. Thanks.
