### ISSUE TITLE
Option to not give message for packages.firegento.com

### ISSUE THREAD

**Issue by peterjaap** [Cotya/magento-composer-installer#120]
We keep getting this message;

you may want to add the packages.firegento.com repository to composer.
add it with: composer.phar config -g repositories.firegento composer https://packages.firegento.com

We do use the Firegento repository, but we're including it through our private Packagist.com repository. Could you create a flag somewhere we can set globally to not show this message?

**Comment by AydinHassan** [comment]
The option already exists: https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/FAQ.md#can-i-disable-repository-suggestions 😄
