### ISSUE TITLE
Mage.php bootstrap split feature will not work with certain versions of Magento EE

### ISSUE THREAD

**Issue by nevvermind** [Cotya/magento-composer-installer#17]
Yes, a certain version of Mage EE has `app/bootstrap.php` already and it'll get ~~overwritten~~ skipped here: https://github.com/Cotya/magento-composer-installer/blob/09dc795e3e3e3bfa36a9619787ddc03deaefc445/src/MagentoHackathon/Composer/Magento/Patcher/Bootstrap.php#L106.

No time for a PR right now. But in case I'll find the time, do you guys have a naming preference? 

This is why it's dangerous to create additional files instead of just patching `Mage.php` (which it's in itself dangerous enough).

**Comment by Flyingmana** [comment]
interesting case,
I never worked with  EE, did not know it has a bootstrap file.

actually the bootstrap file does not get overwritten, but still the Mage.php, which produces problems if it is not correctly added in the bootstrap file.

I dont have a naming preference, I dont even have an idea how to name it without causing confusion.
Had expected a bootstrap.php would be only at people, already patching some parts of the core, so they would need to handle this by hand anyway.

**Comment by nevvermind** [comment]
You're right, it won't be overwritten.
So what do you say if we only change Mage.php and we don't create any other file? You still want tools to be able to change `bootstrap.php`?

**Comment by Flyingmana** [comment]
another possible solution.
Is there some granted way to detect an EE? I think I just want to skip the feature for now in this case.
I dont know the details of EE, the feature may not even be needed there

**Comment by nevvermind** [comment]
EE doesn't have composer autoloader ability. Not yet. EE is about features, not architectural changes.  When EE will have it, CE will have it, too, I guess.

Detecting the edition would be pretty [easy](https://github.com/OpenMage/magento-mirror/blob/cf43f51aab6125f03a0083df1c00ac0f34b86c86/app/Mage.php#L188), but I wouldn't consider it, being irrelevant to the autoloader feature and all.

I do have a working prototype of just changing `Mage.php`. Some rough edges here and there, but working for the most part.

**Comment by Flyingmana** [comment]
ok, it doesnt hurt to try it I think. I will merge your PR for this

**Comment by nevvermind** [comment]
Ok, give some time to prepare it.

**Comment by jonesio** [comment]
I can confirm this is a problem on the latest version of EE (1.14.2). What is the purpose of this feature? The Patcher splits Mage.php into Mage.class.php, Mage.bootstrap.php and bootstrap.php but does not reference them individually anywhere so at present it's pointless?

The issue is that because app/bootstrap.php already exists in EE it (correctly) does not get overwritten but as a result the autoload breaks because Mage.php does still get split...

I'm really not a fan of changing the core files but if necessary It would be helpful to know the purpose of these changes?

**Comment by nevvermind** [comment]
@jonesio - those changes paved way to adding Composer's autoloader to Magento. Alas, from lack of time, the feature remained unfinished. The split between multiple files has another story.

 Also, thanks for the PR, but I'm preparing an autoloading method which doesn't add/overwrite any other files, except changing `Mage.php`. Do you think we can close your PR? For now, you could use the `"extra": { "with-bootstrap-patch": false }` config available starting from the `3.0.3-rc1` release.

**Comment by nevvermind** [comment]
Closing this, as the https://github.com/Cotya/magento-composer-installer/pull/22 PR fixes it

**Comment by jonesio** [comment]
Excellent! Thank you for the explanation.
