### ISSUE TITLE
This vs AOEpeople/composer-installers

### ISSUE THREAD

**Issue by gety9** [Cotya/magento-composer-installer#171]
Guys hi,

It's more a question than an issue. I am just starting using composer for magento. And see 2 options- this repo and https://github.com/AOEpeople/composer-installers.

This repo is much more popular. Could you explain what are the advantages? As far as i understand this repo includes both composer installed and modman functions while AOEpeople/composer-installers is only a composer installer. On the plus side of AOEpeople/composer-installers i see that it includes possibility add to core, while here we need to include https://github.com/AydinHassan/magento-core-composer-installer to do so.

For example of if we take this composer.json using AOEpeople/composer-installers
```
{
    "minimum-stability":"dev",
    "require": {

        "magento/ce": "1.9.1.0",

        "aoepeople/composer-installers": "*",
        "magento-hackathon/indexer-stats":"*",
        "firegento/magesetup":"*",
        "firegento/pdf":"*",
        "integer-net/autoshipping":"*",
        "integer-net/removecustomeraccountlinks":"*",
        "aoepeople/aoe_templatehints":"*",
        "aoepeople/aoe_scheduler":"*",
        "avstudnitz/scopehint":"*",
        "avstudnitz/admin-notification-advanced":"*",
        "tim-reynolds/magento-qconfig":"*",
        "colinmollenhour/cache-backend-redis":"*",
        "colinmollenhour/redis-session":"*",
        "Creare/CreareSEO":"*"
    },
    "repositories": [
	{ "type": "composer",   "url": "http://packages.firegento.com" },
        {
            "type": "package",
            "package": {
                "name": "magento/ce",
                "version": "1.9.1.0",
                "type": "magento-source",
                "dist": {
                    "url": "http://www.magentocommerce.com/downloads/assets/1.9.1.0/magento-1.9.1.0.tar.gz",
                    "type": "tar"
                }
            }
        }	
    ],
    "extra": {
        "installer-paths": {
            "htdocs": ["type:magento-source"],
            ".modman/{$vendor}_{$name}/": ["type:magento-module"]
        }
    },
    "config": {
	"discard-changes": true
    },
    "scripts": {
        "pre-install-cmd": [
            "mkdir -p ./.modman && echo \"htdocs/\" > ./.modman/.basedir"
        ],
        "post-install-cmd": [
            "mv ./htdocs/var ./var",
            "mv ./htdocs/media ./media",
            "ln -rs ./var ./htdocs/var",
            "ln -rs ./media ./htdocs/media"
        ],
        "post-update-cmd": [
            "modman deploy-all --force",
            "n98-magerun cache:flush",
	    "n98-magerun index:reindex:all"
        ]
    }
}
```

would it be easier to achieve same functionality using this project?

**Comment by Flyingmana** [comment]
they depend on the existance of modman as an application, while this Installer here contains already support for modman files, so that is right.

I cant say whats easier by itself, and it depends on your knowledge of things like modman and composer, but experience tells me sticking with what already works for you is usually easier.

This installer has also some additional features which are mostly well described in the Readme.


Feel free to open a new Ticket, if the Readme and linked documents dont answer your remaining questions.
