### ISSUE TITLE
Failed to download magento/magento-composer-installer

### ISSUE THREAD

**Issue by krazonline** [Cotya/magento-composer-installer#172]
Hi,
I m new to magento, and trying to update composer as below and ran into errors.
Guessing its openssl version comptability issue, any thoughts on how to resolve this ?
Searched online but couldnt find leads on this specific issue. 

$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

$ uname -a
Linux ip-10-xxx 4.14.55-62.37.amzn1.x86_64 #1 SMP Fri Jul 20 00:44:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 19 updates, 0 removals
  - Installing magento/magento-composer-installer (0.1.13): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download magento/magento-composer-installer from dist: The "https://api.github.com/repos/magento/magento-composer-installer/zipball/8b6c32f53b4944a5d6656e86344cd0f9784709a1" file could not be downloaded: SSL operation failed with code 1. **OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol**
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing magento/magento-composer-installer (0.1.13): Cloning 8b6c32f53b

                                                                                                                                                         
  [RuntimeException]                                                                                                                                     
  Failed to clone https://github.com/magento/magento-composer-installer.git via https, ssh protocols, aborting.                                          
                                                                                                                                                         
  - https://github.com/magento/magento-composer-installer.git                                                                                            
    Cloning into '/var/www/html/vendor/magento/magento-composer-installer'...                                                                            
    fatal: unable to access 'https://github.com/magento/magento-composer-installer.git/': SSL received a record that exceeded the maximum permissible l  
  ength.

**Comment by Flyingmana** [comment]
wrong repository.
The Project here, is the composer installer for Magento1, while the error points to the magento owned Magento installer which is used for Magento2
