### ISSUE TITLE
Proposal: New deploy-strategy : move

### ISSUE THREAD

**Issue by ProxiBlue** [Cotya/magento-composer-installer#176]
Hello,

We use deploybot to effect deploys to our live server.
After the composer build is done, the symlinked/copied files are copied over to the live server, BUT, the copy process is doubled in time, as the *vendor* folder is also copied, containing copies of all those files just placed into the Magento structure.

Only some packages, not copied to magento needs to stay in the vendor folder, and copied across

If the magento module files are *moved* to the magento structure, the vendor folder will result to be smaller, thus removing a lot of unneeded copy to server time.

I have a working version of this idea here: https://github.com/ProxiBlue/magento-composer-installer/tree/3.1.2-dev

Some feedback would be appreciated, and if you'd like a merge request for such a feature.

TIA

**Comment by Flyingmana** [comment]
this sounds like a very interesting usecase.
Iam generally ok with merging a new method, if it helps someone.

Besides, do you do an atomic deployment to the live server, or an incremental one?
What method do you use for the copy to live server? And how much time is the move method saving?

**Comment by ProxiBlue** [comment]
We are using atomic deploys, with full files deployment. So everything gets copied on each deploy.

Unfortunately, deploybot does this file by file, via sftp. I am discussing with them an option to do a compression to one file, copy, decompression on release folder.

This will be faster than the millions of small files.

Time saved on that depends on number of composer based packages used.

On one site I have measure a 20min reduction, on another hardly any.

**Comment by ProxiBlue** [comment]
Note: all testing of this deploy change has been to UAT deploys. 

Today will be a first to a live deploy.

Will see how that goes, and if result is good, will do a PR

**Comment by Flyingmana** [comment]
Thanks for the insight.

You can already prepare the PR if you want, I will then provide whats necessary to run our integration tests on it.

And compressing it to a single file should improve timing a lot in any case, transfering single files via sftp has quite a lot of overhead :/

**Comment by ProxiBlue** [comment]
PR was done, and deploy to our live servers worked 100% with move deploy strategy
