### ISSUE TITLE
Composer 1.9 Deprecation Notice

### ISSUE THREAD

**Issue by luckyraul** [Cotya/magento-composer-installer#180]
@Flyingmana 
Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate declared at ./vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\PackageEvent but pre-package-update events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:349

**Comment by Flyingmana** [comment]
do you by chance have the composer version used for this?
It seems to not be an Issue with the current or the coming version

**Comment by luckyraul** [comment]
Its is working, but with Deprecation Notice

**Comment by Flyingmana** [comment]
okay, I think the issue could be you are using an old version of the installer.
The related change is here: https://github.com/Cotya/magento-composer-installer/commit/306276fa0dcc12f89bf47ac28d935071efe8a5ba

which version of the installer do you use?


Despite this, there is still an issue with \MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate, which also needs some changes in the related tests

**Comment by Flyingmana** [comment]
should be resolved by having compatibility for Composer v2
https://github.com/Cotya/magento-composer-installer/issues/191
