### ISSUE TITLE
How to use composer vendors and magento webroot?

### ISSUE THREAD

**Issue by razbakov** [Cotya/magento-composer-installer#19]
Is it possible to have this structure:

```
├── src/
│   ├── app/
│   ├── ...
│   ├── vendor/
├── composer.json
```

and in composer.json

```
extra.webroot = src
```

and use php libraries in Magento code like this:

```
use Zend\Soap\Client;
$client = new Client();
```

**Comment by Flyingmana** [comment]
in theory, you can define any directory for vendor.
But, why do you want vendor inside the src/ while the composer.json is outside?
Wouldnt it make more sende, to have the vendor also outside?

**Comment by razbakov** [comment]
I copy to production only content of `src` folder.

**Comment by Flyingmana** [comment]
ok, current state: you can add the include of composers autoload file to the `app/bootstrap.php` as it gets only generated, not overwritten. Include it as first statement before magento.

the vendor should be moved as part of your build script, as I do not know about possible side effects.

but you could try it. see https://getcomposer.org/doc/04-schema.md#config
```
"config": {
     "vendor-dir": "src/vendor"
}
```

**Comment by razbakov** [comment]
Thank you!

How do you think if `vendor` folder should be inside webroot or outside?

**Comment by Flyingmana** [comment]
outside, always, or at least not accessible.

you never know about php files in there, which can harm you
