### ISSUE TITLE
Wrong tag reference?

### ISSUE THREAD

**Issue by Scribblerockerz** [Cotya/magento-composer-installer#2]
It looks like the current 3.0.0 tag lays behind the 2.1.0 tag.
The current version breaks with the following error.

```
PHP Fatal error:  Class 'MagentoHackathon\Composer\Helper' not found in /home/webroot/releases/.../vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 209
```

**Comment by Flyingmana** [comment]
did you update the package?
composer suggests to update installers/plugins only with ```--no-plugins```

**Comment by Scribblerockerz** [comment]
That's not my point. Have a look at the tree:

![version-issue](https://cloud.githubusercontent.com/assets/1336156/6844000/63ad2b5c-d3a8-11e4-8983-2a0e808ea744.png)

I'm not an expert in git versioning, but shouldn't the version 2.1 be behind 3.0?

**Comment by Flyingmana** [comment]
the tree visualization is (can be) misleading, as it does not sort commits correctly by day, but by the time of the head commit.

Maybe https://github.com/Cotya/magento-composer-installer/network visualize this better for this case.

The "problem" is, the 2.1 branch got a commit which was made later then the one in the 3.0.0 branch.
This can happen, as I still accept patches for the 2.1 branch.

**Comment by Scribblerockerz** [comment]
Okay, sorry for this confusion.

**Comment by Flyingmana** [comment]
no problem, 4 eyes see more then 2 :)

is there a problem left, or can I close this issue?

**Comment by Scribblerockerz** [comment]
You can close this ticket.
