### ISSUE TITLE
'mklink""' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by andkirby** [Cotya/magento-composer-installer#20]
Version: 3.0.3-rc.1
```
'mklink""' is not recognized as an internal or external command,
operable program or batch file.
```
Environment: Windows 8.1, Git Bash console.

```
$ git version
git version 1.9.5.msysgit.0
```

P.S. Please fix this and on 2.x version if it exists.

**Comment by mellocapinpin** [comment]
You need to modify this file:
magento-composer-installer\src\MagentoHackathon\Composer\Magento\Deploystrategy\Symlink.php

```
$param = is_dir($absSourcePath) ? ' /D' : '';
exec('mklink' . escapeshellarg($param) . ' "' . escapeshellarg($destPath) . '" "' . escapeshellarg($relSourcePath) . '"');
```

escapeshellarg() function is already putting single quote wrapper to the string, so you need to remove the concatenated double quotes around $destPath and $relSourcePath.

remove escapeshellarg() from $param, this is causing the error when $param='', then replace $param default ('') empty string value to single space.

Modification result:
```
$param = is_dir($absSourcePath) ? ' /D' : ' ';
exec('mklink' . $param . ' ' . escapeshellarg($destPath) . ' ' . escapeshellarg($relSourcePath));
```

**Comment by vovayatsyuk** [comment]
Here is the patch that fixes the issue: https://github.com/magento-hackathon/magento-composer-installer/commit/38b2a4454871a7eba142fda9e65e1230954db29c

It was appied on magento-hackathon/magento-composer-installer, but not here.
