### ISSUE TITLE
Mage.php file sometimes not recreated

### ISSUE THREAD

**Issue by floodedcodeboy** [Cotya/magento-composer-installer#25]
Hi

I'm at a point now where intermittently when using `composer update` after adding additional modules to the Mage.php file ends up missing. I'm using version 3.0.2.

Here is the process I've gone through: 
(NOTE: when i say fail - i mean my magento install is now missing the app/Mage.php file and when i try access it over the web, i am redirected to the Downloader)

1. use only core-composer-installer with preconfigured local.xml as after script - works as expected.
2. add a modman package to composer - and composer update - works as expected
3. require composer-installer and composer update - works as expected
4. delete magento root and vendor folder and do composer install - works as expected
5. require "ebizmarts/magemonkey": “1.1.32” and composer update - works as expected
6. require "connect20/junaidbhura_mandrill” and composer update - works as expected
7. require "connect20/magento4u_customerattribute": “*” and composer update - works as expected
8. require "connect20/mt_switchcompare": “1.3” and composer update - fails!
9. remove "connect20/mt_switchcompare": “1.3” and composer update - returns to normal
10. require "colinmollenhour/modman": “1.12” and composer update - fails
11. remove "connect20/magento4u_customerattribute": “*” and require "colinmollenhour/modman": “1.12” and composer update - fails
12. remove “colinmollenhour/modman” and require "connect20/magento4u_customerattribute” and composer update - works as expected
13. require "floodedcodeboy/fcb_currency-converter" : “*” and composer update - fails
14. require "floodedcodeboy/magento-social-tiles" : “0.1.0” and composer update - returns to normal
15. require "connect20/mt_switchcompare": “1.3” and composer update - fails
16. remove "connect20/mt_switchcompare": “1.3” and composer update - fails

and below is my complete composer.json file: 

```
{
    "name": "floodedcodeboy/magento-shop",
    "description": "Magento Shop",
    "authors": [
        {
            "name": "floodedcodeboy",
            "email": "redacted@mail.com"
        }
    ],
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:bragento/magento-core.git"
        },
        {
           "type": "vcs",
           "url": "https://github.com/cotya/magento-composer-installer"
        },
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        {
            "type": "vcs",
            "url":  "git@github.com:floodedcodeboy/fcb_CurrencyConverter.git"
        },
        {
            "type": "vcs",
            "url":  "https://bitbucket.org/floodedcodeboy/magento-social-tiles.git"
        }
    ],
    "require": {
        "magento/core": "~1.9",
        "aydin-hassan/magento-core-composer-installer": "^1.2.2",
        "colinmollenhour/modman": "1.12",
        "magento-hackathon/magento-composer-installer": "3.0.2",
        "ebizmarts/magemonkey": "1.1.32",
        "connect20/junaidbhura_mandrill": "1.0.4",
        "connect20/magento4u_customerattribute": "*",
        "floodedcodeboy/fcb_currency-converter" : "*",
        "floodedcodeboy/magento-social-tiles" : "0.1.0"
    },
    "extra": {
        "magento-root-dir": "./htdocs",
        "modman-root-dir": ".modman",
        "magento-deploystrategy": "copy",
        "magento-core-deploy" : {
            "git-ignore-append": true
         },
         "auto-append-gitignore": true,
         "magento-force": true
    },
    "config": {
        "preferred-install": "dist"
    },
    "scripts": {
        "localconfig": "cp ./config/app/etc/local.xml ./htdocs/app/etc/",
    }
}
```

**Comment by nevvermind** [comment]
Don't think this package _removes_ Mage.php, but maybe I'm wrong. You sure it's not `aydin-hassan/magento-core-composer-installer`?

**Comment by floodedcodeboy** [comment]
Perhaps.... however his package does not touch the Mage.php file.

**Comment by smithyco** [comment]
I'm having the same problem. When I run a fresh install, it reports that the class "Mage" cannot be found.

Here's my composer.json file. The only package I have in common with the one above besides the hackathon package is the magento-core-installer, so maybe it _is_ the culprit. Maybe some sort of file permissions that's prevent a file from being rewritten or renamed?

```
{
  "name": "my/file",
  "description": "Composer Package",
  "require": {
    "aydin-hassan/magento-core-composer-installer": "^1.2",
    "magento/magento" : "1.14.2.0",
    "magento-hackathon/magento-composer-installer": "3.0.2"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.6"
  },
  "authors": [
    {
      "name": "Edwin Smith",
      "email": "edwin@smithy.co"
    }
  ],
  "repositories": [
    {
      "type": "vcs",
      "url": "github@core.git"
    },
    {
      "type": "composer",
      "url": "http://packages.firegento.com"
    },
    {
      "type": "composer",
      "url": "http://packages.magento.com/"
    }
  ],
  "extra": {
    "magento-root-dir": "./public",
    "magento-core-deploy" : {
        "git-ignore-append": true
     },
     "auto-append-gitignore": true,
     "magento-force": true
  }
}
```

**Comment by smithyco** [comment]
I have to fix two issues to get this working:

1. The bootstrap.php file is not being changed by the Bootstrap.php class. I needed to manually write that file.

2. The index.php file is calling the Mage.php and the bootstrap.php files separately, resulting in a 'require only once' error.

**Comment by nevvermind** [comment]
@smithyco - by the looks of it, you're using Mage EE and a version which already ships with a `app/bootstrap.php`. That may be your problem.

Secondly, have a look at what's changed in 3.0.3 here: https://github.com/Cotya/magento-composer-installer/blob/3.0/CHANGELOG.md - and update your installer to `3.0.3`. That version will tell you if you have permission problems. Make sure you read the docs: https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/Autoloading.md

**Comment by floodedcodeboy** [comment]
So this is still happening and the only way to fix it is to run `composer update` ... again. It's pretty standard that the Mage.php file disappears after adding or removing a new package. wierd. as @smithyco only has the core install as common i'll push this issue over to there.
