### ISSUE TITLE
Autoload not working anymore in magento-composer-installer 3.0.2? Class 'Varien_Profiler' not found in /var/www/app/Mage.class.php on line 637

### ISSUE THREAD

**Issue by kypfr** [Cotya/magento-composer-installer#27]
Hello,

After installing module, my Magento website does not work anymore: Magento is unable to load Varien class:

Fatal error: Class 'Varien_Profiler' not found in /var/www/app/Mage.class.php on line 637

./composer info --installed
> colinmollenhour/modman 1.12 Module Manager

cat composer.json 
>{
 >   "repositories": {
  >      "firegento": {
   >         "type": "composer",
    >        "url": "http://packages.firegento.com"
    >    }
   > },
  >  "require": {
   >     "colinmollenhour/modman": "^1.12"
   > },
   > "minimum-stability": "RC",
   > "extra": {
   >     "magento-root-dir": ".",
>	"magento-deploystrategy": "copy"
 >   }
>}

./composer require magento-hackathon/magento-composer-installer:@stable

> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>  - Installing symfony/console (v2.7.0)
 >   Loading from cache
>
 > - Installing justinrainbow/json-schema (1.4.1)
 >   Loading from cache
>
 > - Installing icecave/isolator (2.3.0)
  >  Loading from cache
>
 > - Installing eloquent/pops (3.1.1)
  >  Loading from cache
>
 > - Installing eloquent/liberator (1.1.1)
 >   Loading from cache
>
 > - Installing eloquent/enumeration (5.1.0)
  >  Loading from cache
>
 > - Installing eloquent/composer-config-reader (2.0.0)
 >   Loading from cache
>
 > - Installing magento-hackathon/magento-composer-installer (3.0.2)
 >   Loading from cache
>
>you may want to add the packages.magento.com repository to composer.
>add it with: composer.phar config -g repositories.magento composer https?://packages.magento.com
>symfony/console suggests installing symfony/event-dispatcher ()
>symfony/console suggests installing symfony/process ()
>symfony/console suggests installing psr/log (For using the console logger)
>icecave/isolator suggests installing eloquent/asplode (Drop-in exception-based error handling.)
>magento-hackathon/magento-composer-installer suggests installing ext-SPL_Types (*)
>magento-hackathon/magento-composer-installer suggests installing theseer/autoload (~1.14)
>Writing lock file
>Generating autoload files

php index.php

> Notice: Use of undefined constant BP - assumed 'BP' in /var/www/app/Mage.class.php on line 964
>
> Notice: Use of undefined constant DS - assumed 'DS' in /var/www/app/Mage.class.php on line 964
>
> Notice: Use of undefined constant BP - assumed 'BP' in /var/www/app/Mage.class.php on line 965
>
> Notice: Use of undefined constant DS - assumed 'DS' in /var/www/app/Mage.class.php on line 965

> Fatal error: Class 'Varien_Profiler' not found in /var/www/app/Mage.class.php on line 637

cat app/Mage.php

> <?php
>require __DIR__ . '/bootstrap.php';
(This is well __DIR__ constant, but formatter hide the _).

cat app/bootstrap.php 
><?php
>require __DIR__ . '/Mage.class.php';
>require __DIR__ . '/Mage.bootstrap.php';

(This is well __DIR__ constant, but formatter hide the _).

tail -10 app/Mage.class.php

>/** AUTOLOADER PATCH **/
>if (file_exists($autoloaderPath = BP . DS . '../vendor/autoload.php') ||
>    file_exists($autoloaderPath = BP . DS . 'vendor/autoload.php')
>) {
>    require $autoloaderPath;
>}
>/** AUTOLOADER PATCH **/

(This is well __DIR__ constant, but formatter hide the _).

Magento version: CE1.9.1

php -version

> PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51) 
> Copyright (c) 1997-2014 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
>    with the ionCube PHP Loader v4.7.4, Copyright (c) 2002-2014, by ionCube Ltd., and
>   with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

If you require any further additional information, let me know.
Regards

**Comment by nevvermind** [comment]
You had your `Mage.php` file split by the pre-3.0.3 bootstrap feature into `app/bootstrap.php` and `app/Mage.class.php` and now you've applied the 3.0.3-rc bootstrap feature on it. The new 3.0.3-rc bootstrap feature requires a clean `Mage.php` file, not 
```php
<?php
require DIR . '/bootstrap.php';
```
See the [changelog](https://github.com/Cotya/magento-composer-installer/blob/3.0/CHANGELOG.md#303-rc2---2015-05-20). Also, the [autoloading docs](https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/Autoloading.md).

Simple fix:
a) Remove `app/bootstrap.php` and `app/Mage.class.php`;
b) Revert `app/Mage.php` to its original state;
c) Assuming you already have this installer, run `composer update` or require it again if you don't. This will re-apply the bootstrap patch on a clean `Mage.php`.

If you don't want the patching to happen, use a Composer `extra` setting: `"with-bootstrap-patch": false`.

PS: use `composer require magento-hackathon/magento-composer-installer:@dev`, instead of lowering the stability for **all** packages with `"minimum-stability": "RC"`. I've been told a stable release will be happening soon (tomorrow?), so you can then just use `composer require magento-hackathon/magento-composer-installer:3.0.3`.

**Comment by kypfr** [comment]
Hello,

your tip to rollback is fine, thanks you.

It could be interesting if you patch the app/Mage.php to made from the module side a backup: I need to download a second time Magento source code to be able to find the original app/Mage.php file.

I'm not sure if I need to patch or not, for now I prefer use your default policy: my aim is only to made your module work to install mines :)

And thanks for your tip regarding minimum-stability. I should explain quit a bit longer why I use this module: I test my own module from my composer repository in this composer file (which was not complete). This was the testing composer.json: RC was set to make myself able to test my RC releases from my testing composer repository.

Anyway, thanks for your very quick answer, it was just amazing!

Regards.

**Comment by craigcarnell** [comment]
@nevermind Did this ever happen? The git readme still says 3.0.2

**Comment by adragus-inviqa** [comment]
@craigcarnell - not sure I understand what you mean.

**Comment by nevvermind** [comment]
@craigcarnell - not sure I understand what you mean.

**Comment by craigcarnell** [comment]
@nevvermind For those who install via following the git readme, it still tells you to install 3.0.2

**Comment by nevvermind** [comment]
You mean https://github.com/Cotya/magento-composer-installer#update-the-installer? Yeah, don't.

**Comment by Flyingmana** [comment]
this describes updating, not installing....
It also says to read the composer documentation.

Anyway, changed to use a non explicite version
