### ISSUE TITLE
/app/Mage.php is not a file

### ISSUE THREAD

**Issue by luckyraul** [Cotya/magento-composer-installer#31]
on first install via composer install for module without magento
[InvalidArgumentException]    
  ./app/Mage.php is not a file

**Comment by nevvermind** [comment]
Seems ok to me, right? You install it _without_ Magento.

Try `composer install --no-plugins` if you wish to avoid the hackathon plugin altogether.

**Comment by AydinHassan** [comment]
Maybe it shouldn't just die if the file doesn't exist?

**Comment by luckyraul** [comment]
yep, It is ok, but it ruins all my tests (

**Comment by nevvermind** [comment]
> yep, It is ok, but it ruins all my tests

I understand, but that's not a problem of this installer, now, is it? This plugin assumes a valid environment. If it's not, it shouldn't do anything BUT fail. Would you want this to work on a Drupal installation? There are ways to make your scenario work (see below).

First of all, it's _not_ dying and it _is_ checking if the file exists: https://github.com/Cotya/magento-composer-installer/blob/f8d517b67a7d9db7cbd0da467c03e9d191bebe3e/src/MagentoHackathon/Composer/Magento/Patcher/Bootstrap.php#L76-L77

It just assumes a Magento codebase is in place, is all. Again, use `--no-plugins` when installing Magento modules with no Magento, otherwise, this plugin's logic rightfully kicks in. Or maybe `--no-scripts` is enough.

**Comment by luckyraul** [comment]
No, It is magento. 
I use plug-in for installing module dependencies for my module.
I think it should be not an exception, just notice.

**Comment by nevvermind** [comment]
> No, It is magento. 

Yeah, I've been saying this for years, too.

> I think it should be not an exception, just notice. 

A notice will give the message that it's _ok-ish_ to NOT have Magento in place before installing you module. How is it ok to have not have Magento in the first place? (except standalone testing ofc, in which case you'd use `--no-plugins`).

`Mage.php` is needed first of all to check if the modules are to be installed on a _valid_ environment and secondly, by having standard folders (like `app`) and files (like `app/Mage.php`) in place, we can discern where we were, thus figuring out the path to install the modules.

What `composer.json` do you have anyway and what commands do you use when you see the error?

**Comment by AydinHassan** [comment]
@nevvermind I disagree, this plugin's sole job is to place modules in the correct place. An installation of Magento is NOT required. There may be a possibility where you install the core via a different method, and it may so be that it runs after your module installation.

**Comment by nevvermind** [comment]
> this plugin's sole job is to place modules in the correct place

What's the correct place in the scenario in which Magento codebase is not there? You mean `vendor`?

**Comment by luckyraul** [comment]
>What's the correct place in the scenario in which Magento codebase is not there? You mean vendor?

I guess ```magento-root-dir```

**Comment by nevvermind** [comment]
> There may be a possibility where you install the core via a different method, and it may so be that it runs after your module installation.

Is that even a valid scenario? I mean, is it only me, or installing Magento _after_ installing modules sounds at least wierd? How you keep Magento from not overwriting you already-in-place modules?

So your saying that this plugin is just a glorified modman? Yeah, sure, it can be. I thought of it as more.

**Comment by nevvermind** [comment]
@luckyraul - add `{ "extra": { "with-bootstrap-patch": false } }` in your composer.json, then try installing again.

**Comment by luckyraul** [comment]
with ```"with-bootstrap-patch": false``` - no change

**Comment by nevvermind** [comment]
Can I still have that composer.json of yours?

**Comment by luckyraul** [comment]
"require": {
        "magento-hackathon/magento-composer-installer": "*",
        "mygento/somemodule":"*",
"mygento/somemodule1":"*",
"mygento/somemodule2":"*",
"mygento/somemodule3":"*"
    },
"extra": {
        "magento-root-dir": ".",
	"with-bootstrap-patch": false
    }

**Comment by Flyingmana** [comment]
if the issue still occurs, feel free to reopen

**Comment by nevvermind** [comment]
@luckyraul - you'll need to change you're require to `"magento-hackathon/magento-composer-installer": "@dev"` until this will be released.

**Comment by caneraydinbey** [comment]
What is solution?
