### ISSUE TITLE
Requiring dev-master packages does not trigger deploy unless there is no entry in installed.json.

### ISSUE THREAD

**Issue by unknownnf** [Cotya/magento-composer-installer#33]
For dev-master packages version in installed.json is always `9999999-dev` and redeploy does not trigger automatically after updates.

Should come from: https://github.com/Cotya/magento-composer-installer/blob/3.0/src/MagentoHackathon/Composer/Magento/Repository/InstalledPackageFileSystemRepository.php#L110.

**Comment by AydinHassan** [comment]
Ah good spot. I'll write a patch for this next week unless anybody gets around to a quicker. I guess we should just always redeploy packages with that version.

**Comment by Flyingmana** [comment]
:+1:

**Comment by unknownnf** [comment]
Just blacklisting `9999999-dev` is probably not enough, further digging revealed:

https://github.com/composer/composer/blob/17c2a8019eb9692ddb9ce7ac067d2b7bcb487ad3/src/Composer/Package/Version/VersionParser.php#L112-L118

So basically, `dev-master`, `dev-trunk` and `dev-default` all return `9999999-dev` but `dev-develop` or `dev-feature-branch-x` will return themselves as they are.

https://github.com/Cotya/magento-composer-installer/blob/3.0/src/MagentoHackathon/Composer/Magento/ModuleManager.php#L172 is the part where magento-composer-installer filters these and where the issue comes from, probably returning false for all `99999999-dev` and `dev-*` versions is the proper fix here.

**Comment by AydinHassan** [comment]
@Flyingmana this can be closed now
