### ISSUE TITLE
Should we consider public Class Methods and Interfaces in version regarding BC breaks?

### ISSUE THREAD

**Issue by Flyingmana** [Cotya/magento-composer-installer#37]
As recently there were some objections regarding the change of an Interface, as it means a BC break, I want to discuss this here.

While I see the point in general, I want to point out, this project is a tool, a Plugin, not a library.

I would be happy to see people reuse code from this project, But as far as I know, this does not happen yet. If someone knows another Project which does this, I would like to know.

If we decide this to be public APIs we want to support, then we should add documentation and tests for them, too.

But, I would prefer to not support them, and instead sit together and put the needed code into a separate library shared between projects.

**Comment by AydinHassan** [comment]
The only reason I objected was because it wasn't necessary

**Comment by nevvermind** [comment]
This installer is already losing trust by breaking stuff more often than it should without bumping the major version.

Changing a public API without changing the major version should _not_ be taken lightly. And if it does come to that, it better be well justified.
