### ISSUE TITLE
Invalid JSON written for magento-root-dir

### ISSUE THREAD

**Issue by ktomk** [Cotya/magento-composer-installer#45]
I don't know if this still applies to the current version, just ran over it with a fresh composer install.

When the interactive installation routine asks for the magento installation directory that value is put into composer.json then.

This writing the input into composer.json is flawed. The input is not properly encoded as JSON value.

Enter character sequences like "c:\tmp\magento" for example, next time composer install is run you see errors:

```
 composer install



 [Seld\JsonLint\ParsingException]
 "./composer.json" does not contain valid JSON
 Parse error on line 17:
 ..."magento-root-dir": "c:\tmp\magento"
 ----------------------^
 Invalid string, it appears you have an unescaped backslash at: \m



nstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [
-no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
```

**Comment by Flyingmana** [comment]
probably not fixed, I think is only on windows a problem?

**Comment by tkn98** [comment]
As far as you're concerned about POSIX systems, you're right that these use \<slash> and not \<backslash> within pathnames.

However that is unrelated to destroying the full composer.json from further parsing by not encoding values properly when the file is modified.

So I'd say it's a problem with not properly encoding the JSON. So it's perfectly possible to use "\" characters on linux as well. Not doing the encoding is the flaw. So doing the encoding will fix this flaw.

**Comment by tkn98** [comment]
Just tested in a linux box using

    hello \" world!

as root dir, it's properly encoded as

    "hello \\\" world!"

within composer.json. So most likely this problem does not exist any longer?

**Comment by ktomk** [comment]
I could now look now again on that windows box: In the project where I had the issue the requirements there only cover magento composer installer

~~~~
...
    "require": {
        "magento-hackathon/magento-composer-installer": "*"
    },
...
~~~~

From what I could locate w/o debugging is that **MagentoHackathon\Composer\Magento\ProjectConfig** is using **Composer\Json\JsonManipulator** to manipulate the file. @AydinHassan was giving the hint this might be an upstream problem.

As far as I can see in that project which is requiring magento-composer-installer, after running composer install, all those composer base classes are not part of the actual dependencies. Is this perhaps a hole in the composer configuration of magento-composer-installer? What I mean is, could it be that *magento-composer-installer* magically thinks all composer requirements will be there w/o a require of them? Perhaps from the expectation that "all" composer requirements must be there, because it is a composer installer?
