### ISSUE TITLE
Possible to backport fixes to 98 and 139 to 2.1 branch?

### ISSUE THREAD

**Issue by kojiromike** [Cotya/magento-composer-installer#53]
https://github.com/magento-hackathon/magento-composer-installer/issues/98 and https://github.com/magento-hackathon/magento-composer-installer/issues/139 don't appear to be fixed in 2.1. The referenced commit does not apply cleanly to the HEAD of 2.1 now. I will see if I can backport this fix if I have time later, but I thought I'd open an issue in case someone more familiar with the code already knows how to do it quickly.

**Comment by AydinHassan** [comment]
There is a lot of changes to make this happen (the state-tracking that is) too much to back-port. Can you not just use `https://github.com/magento-hackathon/composer-command-integrator` and use the `magento-module-deploy` command ?

That should deploy all modules.

Is there any reason why you can't update to 3.x ?

**Comment by kojiromike** [comment]
I know a lot of people pinned 2.1 because of the core hack in 3. (They may not realize that you can disable that core hack with configuration.) Our own operations team will not update past 2.1 for a project for stability and opsy reasons, but they are more likely to accept a patch. I've made all the arguments, but they aren't willing to update right now.

I will discuss the possibility of just always running cci magento-module-deploy after every update.

**Comment by AydinHassan** [comment]
Trying to patch 2.1 is likely going to be more risky than updating to 3.0. The internals have changed a lot since then.

**Comment by Flyingmana** [comment]
If you have a PR for the 2.1 Branch, it will likely get merged, but I don't think it will get fixed from one of the maintainers. Maybe if you hire one of them.

**Comment by Flyingmana** [comment]
as composer V1 is outdated soon, and Version 2 of the installer is definitely not able to support Composer Version 2, I will close this
