### ISSUE TITLE
Make Contributions show up in profile of contributors

### ISSUE THREAD

**Issue by AydinHassan** [Cotya/magento-composer-installer#60]
Can we remove the `master` branch and move `3.0` to `master`

It's annoying when creating PR's and contributions to the repository only show for `master` branches, or that could be because this repository is a fork?

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

Maybe we should remove the fork association and just link back to the original?

**Comment by Flyingmana** [comment]
`master` seems to be not the problem, as the link says a bit down the default branch is also ok.

Removing the fork reference may be point needed here

**Comment by Flyingmana** [comment]
and fork is detached, activity now shows up in my and also your profile

**Comment by AydinHassan** [comment]
Awesome thanks! :)
