### ISSUE TITLE
Varien_Autoloader patching instead of Mage for autoloading

### ISSUE THREAD

**Issue by dav-m85** [Cotya/magento-composer-installer#66]
Maybe it is a bit naive question, but have you considered overriding the Varien_Autoloader class to include composer loading instead of patching the Mage class ?

Like you know, creating a local/Varien/Autoloader.php.

This third option is not debated in https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/Autoloading.md and then I'm wondering.

**Comment by nevvermind** [comment]
Some community modules overwrite it themselves. We aimed for 100%. 

http://www.webguys.de/magento/tuerchen-11-the-magento-autoloader-and-external-libraries/

**Comment by Flyingmana** [comment]
yeah, overriding classes always makes problems over time, especially if more then one Module tries to do this.
