### ISSUE TITLE
Should my module require the Installer: No

### ISSUE THREAD

**Issue by josephmcdermott** [Cotya/magento-composer-installer#68]
If my third party modules do not contain:
```
"require": {
    "magento-hackathon/magento-composer-installer":"*"
}
```

... then the correct installation cannot be guaranteed. If composer installs my module *before* the magento installer, the symlinking process will not take place for that module. The only way I have found to guarantee the installer comes before each module is to add the above require.

Unless I have missed something (I'm hoping I have...)

**Comment by Flyingmana** [comment]
the most recent 3.x version is done in a way, which makes the order of installs irrelevant.
So even if you add the installer at a later time, it should add all the symlinks.

When you have a case where this does not happen, please provide a composer.json so we can try to reproduce this.

**Comment by josephmcdermott** [comment]
Ah ok will give that a try. I use "*" for your module version which pulls in the master branch, and that has not been updated for a while so I'm missing the latest changes. Thank you for the fast response.

**Comment by josephmcdermott** [comment]
Confirmed version 3.0.5 works well, much appreciated.
