### ISSUE TITLE
[Exception] Package "vendor/name" is already installed

### ISSUE THREAD

**Issue by barryvdh** [Cotya/magento-composer-installer#7]
I have a composer json with 3 packages in a private repository. 1 of those depends on another of those. When I install the packages, I get an error that a package is already installed, so it doesn't continue and the packages aren't installed.
Removing the Exception from https://github.com/Cotya/magento-composer-installer/blob/1a15c8a83c61c487580ef63da820f4a90030e095/src/MagentoHackathon/Composer/Magento/Repository/InstalledPackageFileSystemRepository.php#L132 does continue the install..

Below is my composer.json. Do I need to run it first with just magento-hackathon or is there anything other I need to keep in mind?

    "require": {
            "php": ">=5.4.0",
            "magento-hackathon/magento-composer-installer": "3.x",
            "myvendor/package1-base": "dev-master",
            "myvendor/package1": "dev-master",
            "myvendor/package2": "dev-master"
        },
        "repositories": [
            {
                "type": "composer",
                "url": "http://packages.firegento.com"
            },
            {
                "type": "vcs",
                "url": "git@bitbucket.org:myvendor/package1-base.git"
            },
            {
                "type": "vcs",
                "url": "git@bitbucket.org:myvendor/package1.git"
            },
            {
                "type": "vcs",
                "url": "git@bitbucket.org:myvendor/package2.git"
            }
        ],
        "extra":{
            "magento-root-dir": "htdocs/",
            "auto-append-gitignore": true
        }
    }

**Comment by Flyingmana** [comment]
this may be a bug, could you try to create some example packages for me to test this?
you can submit them as PR into this directory https://github.com/Cotya/magento-composer-installer/tree/3.0/tests/res/packages

**Comment by bencorlett** [comment]
I've had nothing but issues with `3.*` :( I've just reverted to the `2.*` flavour which didn't have this bug.

**Comment by bencorlett** [comment]
@barryvdh have you had any luck? Several times I've tried to upgrade to this `3.x` but run into the same issue, every single time.

**Comment by barryvdh** [comment]
No,  I reverted to 2.x for now..

**Comment by AydinHassan** [comment]
This is probably my fault, sorry. I'll try reproduce it and fix it when I get some time. If it is what I think it is, possibly a simple fix

**Comment by Flyingmana** [comment]
I think it has something to do with entries inside the `var/installed.json` from an earlier try. Maybe the problem vanishes if they delete it before.

**Comment by bencorlett** [comment]
Nope, a nuke of the vendor folder doesn't help. 

I'm going to look into this today when I get to work. 

Sent from my iPhone

Please excuse my brevity

**Comment by Flyingmana** [comment]
you misunderstood me, the installed.json is not part of the vendor, its part of the targeted magento path

**Comment by bencorlett** [comment]
I thought you said vendor/json. It's 6am, far too early for me to email responsibility lol. 

Sent from my iPhone

Please excuse my brevity

**Comment by AydinHassan** [comment]
@Flyingmana It is currently stored in the vendor dir: https://github.com/Cotya/magento-composer-installer/blob/3.0/src/MagentoHackathon/Composer/Magento/Plugin.php#L220

**Comment by Flyingmana** [comment]
ahh right... then the change of this only exists in my head yet...

**Comment by AydinHassan** [comment]
OK I think I've figured out the issue here. When using branch aliased packages, when we ask composer for all of the installed packages, we get two packages for the ones which are branch aliased, hence the exception being thrown: 

![screen shot 2015-06-10 at 12 43 15](https://cloud.githubusercontent.com/assets/2817002/8081677/b1a53c6c-0f6e-11e5-9508-577287e4e24e.png)

So the fix here is to ignore aliases packages.

**Comment by AydinHassan** [comment]
@barryvdh can you confirm that your packages are also branch-aliased?

**Comment by barryvdh** [comment]
Yeah I'm also using branch-aliasing to restrict my dev versions.

**Comment by AydinHassan** [comment]
awesome. A proper fix is incoming soon.

**Comment by nevvermind** [comment]
@AydinHassan - what about https://github.com/Cotya/magento-composer-installer/pull/34? Are you reverting that, or adding to it etc.?

**Comment by AydinHassan** [comment]
@nevvermind I'm going to propose reverting it and fix #34 in a simpler manner. I'll ping all you dudes when it's ready for review.

**Comment by nevvermind** [comment]
As a PR is already a proposition, so you should revert it _in your PR_. Everything in one, single, squashed commit. :stuck_out_tongue:
