### ISSUE TITLE
Install Magento Core

### ISSUE THREAD

**Issue by flancer64** [Cotya/magento-composer-installer#71]
Hello, guys.

You wrote: _If you want to install the Magento Core, you should try AydinHassan/magento-core-composer-installer as additional plugin._

I want to install Magento Core but I cannot setup 2 modules with the same name "magento-hackathon/magento-composer-installer" in my composer.json.

This project has this name in it's own "[composer.json](https://github.com/Cotya/magento-composer-installer/blob/3.0/composer.json#L2)" and AydinHassan/magento-core-composer-installer project has the same [name](https://github.com/AydinHassan/magento-module-composer-installer/blob/master/composer.json#L2).

Sorry, I don't understand how I can use two different composer packages with the same name?

Could I install all modules and Magento Core (version 1) using one only plugin or I should setup both of them? How I can do second one?

Thanks,

Alex.

**Comment by AydinHassan** [comment]
@flancer64 Wrong project. It is https://github.com/AydinHassan/magento-core-composer-installer. It doesn't have the same name :)

**Comment by flancer64** [comment]
Yes, it is :)

It's my own glitch.

Thanks a lot.
