### ISSUE TITLE
Patching of Mage.php is broken when using get.php

### ISSUE THREAD

**Issue by LeeSaferite** [Cotya/magento-composer-installer#72]
The get.php script does not define the BP constant for some strange reason. The Mage.php patching code expects this to exists.

**Comment by Flyingmana** [comment]
the current implementation puts the patching after the first Varien_Autoload occurence, as the Mage.php sets itself the BP constant I assume this issue is fixed in the most recent version.

If Iam wrong feel free to reopen the issue.
