### ISSUE TITLE
Does magento-composer-installer support magento2-community-edition?

### ISSUE THREAD

**Issue by flancer64** [Cotya/magento-composer-installer#78]
Hello, guys.

I have tried to install Magento 2 using [magento-composer-installer](https://github.com/Cotya/magento-composer-installer) and [magento2-community-edition](https://github.com/magento/magento2-community-edition). I have an error:

	Fatal error: Cannot use Composer\Installer as Installer because the name is already in use in phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 12

	Call Stack:
		0.0001     236200   1. {main}() /usr/bin/composer:0
		0.0034     419528   2. require('phar:///usr/bin/composer/bin/composer') /usr/bin/composer:25
		0.0279    3748320   3. Composer\Console\Application->run() phar:///usr/bin/composer/bin/composer:43
		0.0300    4098992   4. Symfony\Component\Console\Application->run() phar:///usr/bin/composer/src/Composer/Console/Application.php:98
		0.0319    4236152   5. Composer\Console\Application->doRun() phar:///usr/bin/composer/vendor/symfony/console/Application.php:120
		0.0331    4358016   6. Symfony\Component\Console\Application->doRun() phar:///usr/bin/composer/src/Composer/Console/Application.php:163
		0.0331    4358456   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/bin/composer/vendor/symfony/console/Application.php:189
		0.0332    4359032   8. Symfony\Component\Console\Command\Command->run() phar:///usr/bin/composer/vendor/symfony/console/Application.php:838
		0.0338    4364112   9. Composer\Command\InstallCommand->execute() phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:256
		0.0719    8564944  10. Composer\Installer->run() phar:///usr/bin/composer/src/Composer/Command/InstallCommand.php:134
		0.0780    8685288  11. Composer\Installer->doInstall() phar:///usr/bin/composer/src/Composer/Installer.php:232
	  337.7136  356983664  12. Composer\Installer\InstallationManager->execute() phar:///usr/bin/composer/src/Composer/Installer.php:603
	  337.7136  356983712  13. Composer\Installer\InstallationManager->install() phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:139
	  337.7137  356983816  14. Composer\Installer\PluginInstaller->install() phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:152
	  340.0265  357022576  15. Composer\Plugin\PluginManager->registerPackage() phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php:62

This is my [composer.json](https://github.com/flancer32/sample_mage2_module/blob/860a3f4f101fc418c9ff62cf1da66d1311c0d428/live/composer.json) (I have removed all extra dependencies here):

	"require": {
		"magento-hackathon/magento-composer-installer": "dev-master",
		"magento/product-community-edition": "2.0.0"
	}

Is it possible to install Magento 2 using Cotya/magento-composer-installer?

Best regards,

Alex Gusev.

**Comment by Flyingmana** [comment]
No, you dont need this installer

please read the magento 2 Documentation for this.
