### ISSUE TITLE
AWeberCommunications_EmailMarketing.json 404 error

### ISSUE THREAD

**Issue by bumblebears** [Cotya/magento-composer-installer#79]
I'm trying to run composer update and keep running into the following issue:

[Composer\Downloader\TransportException]                                                                                            
  The "http://packages.firegento.com/AWeberCommunications_EmailMarketing.json" file could not be downloaded (HTTP/1.1 404 Not Found)

We have tried everything we can think of and backed out all of our composer requirements except magento-composer-installer.  We still get the error.  

When we go to packages.firegento.com we can download AWeberCommunications_EmailMarketing as a tar, but we cannot get to the .json link above. 

Any ideas?

**Comment by kirmorozov** [comment]
+1

**Comment by gdemad** [comment]
+1

**Comment by craigcarnell** [comment]
Getting the same error, please fix ASAP!

**Comment by azngeek** [comment]
+1

**Comment by bumblebears** [comment]
Just tried again this morning, not getting the error anymore. Thank you!

**Comment by adragus-inviqa** [comment]
Why do you all you guys think it's this module's fault?

**Comment by ajpevers** [comment]
either it's solved or `composer selfupdate` and `composer update` did the trick

**Comment by bumblebears** [comment]
I ran composer update several times yesterday without any resolution.  After running composer update this morning the issue appears to be resolved.  I will mark as closed as someone else has seen resolution as well.

@adragus-inviqa I'm not sure this was the module's fault, but this is the package that has the dependency on AWeberCommunications_EmailMarketing, so I was hopeful someone here would know how to solve the problem. 

Thank you all!
