### ISSUE TITLE
Mage.php strange patching 

### ISSUE THREAD

**Issue by will-b** [Cotya/magento-composer-installer#86]
Mage.php is missing a quote.
Mage.bootstrap.php has no php tags
Mage.class.php

![screen shot 2015-12-15 at 13 02 19](https://cloud.githubusercontent.com/assets/1074708/11809166/9eb83d9a-a32d-11e5-9331-98f3e98d73d4.png)
![screen shot 2015-12-15 at 13 02 25](https://cloud.githubusercontent.com/assets/1074708/11809167/9ece9bf8-a32d-11e5-9b71-af56ded7e416.png)
![screen shot 2015-12-15 at 13 02 09](https://cloud.githubusercontent.com/assets/1074708/11809168/9ed9936e-a32d-11e5-9b82-9b1d0428c7cc.png)

Anyone else getting this?

**Comment by AydinHassan** [comment]
Which version of the installer are you using? Try updating to the latest version.

**Comment by will-b** [comment]
Sorry was pulling in an old version (3.0.0) using 3.0.6 now. Is fixed.

**Comment by AydinHassan** [comment]
Nice! :smile:
