### ISSUE TITLE
Not Symlinking all Required Repos..

### ISSUE THREAD

**Issue by brandontamm** [Cotya/magento-composer-installer#87]
Problem: Composer clones my “require”d repos to the vendor directory, but is not symlinking them into the Magento core files.

Background: I am using the setup at https://github.com/andreaskoch/dockerized-magento. The modules that Andreas had listed there are correctly symlinking. The magento core that i added installs correctly and works just fine, but the three other repos I added are not. The repos are connected to packagist via github. My Magento core is installing correctly, but the two modules and the one theme repo is not. My composer.json is here: http://pastebin.com/gTpKQy8K#

Solution: Can you help? :-)

**Comment by AydinHassan** [comment]
A quick look at https://github.com/brandontamm/ceg-quickattach shows you have no module mappings and also not the correct package type. Package type is `magento-module` not `magento-theme`.

Please check the documentation: 

* [Make A Module Installable With Composer](https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/MakeAModuleInstallableWithComposer.md)

* [Mappings](https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/Mapping.md)

Feel free to come back with any more questions after you have read and tried the docs, but all of your questions should be answered there :smile:

**Comment by AydinHassan** [comment]
Also please note that https://github.com/andreaskoch/dockerized-magento is using an old version of the installer, which has many missing features and bug fixes.

**Comment by brandontamm** [comment]
@AydinHassan  - I realize that project is using the older version and I would like to swap it out for your module. Will it work to just replace the older version with your version in the composer.json files?

Thank you again for your help!
