### ISSUE TITLE
Setting extra.magento-root-dir does not exist 

### ISSUE THREAD

**Issue by 0m3r** [Cotya/magento-composer-installer#88]
When I run command from manual [install-a-module-in-your-project](https://github.com/Cotya/magento-composer-installer#install-a-module-in-your-project)
I get an error
~~~bash
composer config extra.magento-root-dir composer "htdocs/"
                                                                                     
  [InvalidArgumentException]                                                         
  Setting extra.magento-root-dir does not exist or is not supported by this command  

~~~

/var/www/html$ composer --version 
Composer version 1.0-dev (f25446e507a3f420b2b88e6dedc47787d42ea7e9) 2015-12-15 09:35:39

**Comment by Flyingmana** [comment]
composer may have changed the api for this command, and it seems we cant use this anymore.
You will have to set it directly in the composer.json for now.

**Comment by 0m3r** [comment]
but I can't edit directly  :( 

https://stackoverflow.com/questions/33568749/use-composer-cli-to-add-data-to-the-extra-property

jq --indent 4 '.extra.foo = "bar"' composer.json | sponge composer.json
