### ISSUE TITLE
$this when not in object context

### ISSUE THREAD

**Issue by fidellakis** [Cotya/magento-composer-installer#89]
After installing composer on project this exception shows when running "composer update" 

PHP Fatal error:  Using $this when not in object context in /var/www/weseebeauty/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/ModuleManager.php on line 172

**Comment by Flyingmana** [comment]
Which version of the installer do you have? This error looks odd, and I wonder how it could happy at all with the current version

**Comment by fidellakis** [comment]
running version 
Composer version 1.0-dev (f31799b739265e7cb1797b395050ffcd57671335)

**Comment by Flyingmana** [comment]
Thats the version of composer, via ``composer show -i`` you should be able to see the installed versions of packages. I need the one for the composer installer

**Comment by AydinHassan** [comment]
Most likely using commit e0d8d4ffe52e08ca60ffed43aca207376bc48b93 or before and most definitely using PHP 5.3.

Update to the latest version of the installer and you will probably receive an error saying your PHP version is not supported. We did not specify the required version of PHP before even though we used 5.4 features :smile:

**Comment by Flyingmana** [comment]
If thats the case, I would refer to https://github.com/Cotya/magento-composer-installer#supported-php-versions

**Comment by fidellakis** [comment]
magento-hackathon/magento-composer-installer 3.0.4, and definitely using PHP 5.3

**Comment by AydinHassan** [comment]
@fidellakis Although not specified in the composer configuration, `3.0.4` requires PHP 5.4 at a minimum.

**Comment by fidellakis** [comment]
thx guys!!!
