### ISSUE TITLE
composer-plugin-api version error

### ISSUE THREAD

**Issue by 7ochem** [Cotya/magento-composer-installer#93]
When doing `composer update` on any project, I'm getting the following warning/error:

> The "magento-hackathon/magento-composer-installer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by adragus-inviqa** [comment]
You're using an older version. The latest has [a more relaxed API constraint](https://github.com/Cotya/magento-composer-installer/blob/3.0/composer.json#L45).

**Comment by 7ochem** [comment]
I see, thank you for pointing me out.

**Comment by 7ochem** [comment]
What about version 2? That still has the hard `1.0.0` constraint...

**Comment by adragus-inviqa** [comment]
It can still be backported to version 2, I guess. Something for @Flyingmana to consider.

**Comment by Flyingmana** [comment]
No problem, if there is a PR for the 2.x branch, i will merge it when iam home. But i dont offer free support if there are problems.

Speaking about problems, what problems prevent you from updating? I tought they were mostly resolved

**Comment by Flyingmana** [comment]
Should be fixed I think, release will come soon
